---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
# - name: build-push
#   pull: always
#   image: golang:1.14
#   commands:
#   - go build -v -a -o docker-demo
#   environment:
#     CGO_ENABLED: 0
#   when:
#     event:
#       exclude:
#       - tag

- name: publish
  pull: always
  image: plugins/docker:linux-amd64
  environment:
    DOCKER_BUILDKIT: 1
  settings:
    auto_tag: true
    cache_from: appleboy/gin-docker-demo
    daemon_off: false
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: appleboy/gin-docker-demo
    username:
      from_secret: docker_username
  when:
    event:
      exclude:
      - pull_request
